name: Add updated Readme to PRs

on: 
  pull_request:
    paths:
      - charts/**

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: install helm-docs
        run: |
          curl -sSfLO https://github.com/norwoodj/helm-docs/releases/download/v1.5.0/helm-docs_1.5.0_Linux_x86_64.tar.gz
          tar xvfz helm-docs_1.5.0_Linux_x86_64.tar.gz -C /tmp
          rm -f helm-docs_1.5.0_Linux_x86_64.tar.gz 
          chmod +x /tmp/helm-docs
          mv /tmp/helm-docs /usr/local/bin/
      
      - name: generate updated chart readme
        run: helm-docs -o charts/cluster-overprovisioner/README.md 
      
      - name: push updated chart readme
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add charts/cluster-overprovisioner/README.md
          git commit -m "Auto-Update Chart Readme"
          git push origin HEAD:$GITHUB_HEAD_REF
